version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: movie_app_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_app
    ports:
      - "5433:5432"
    networks:
      - movie_app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - movie_app_network


networks:
  movie_app_network:
    driver: bridge

volumes:
  postgres_data:
