services:
  movie_app_db:
    image: postgres:latest
    container_name: movie_app_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - movie_app_network

  movie_app_pgadmin:
    image: dpage/pgadmin4
    container_name: movie_app_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - movie_app_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - movie_app_network

volumes:
  pgadmin_data:

networks:
  movie_app_network:
    external: true